import React, {useEffect, useState} from 'react'
import { useRouter } from 'next/router'
import Sidebar from '../../components/Sidebar'
import Widgets from '../../components/Widgets'
import Head from 'next/head'
import CommentModal from '../../components/CommentModal'
import { ArrowLeftIcon } from '@heroicons/react/solid'
import Post from '../../components/Feed/Post'
import { db } from '../../firebase'
import { doc, onSnapshot } from 'firebase/firestore'

const PostPage = ({ newsData, whoToFollowData }) => {
    const router = useRouter();
    const { id } = router.query;
    const [post, setPost] = useState(null);

    useEffect(()=> {
        onSnapshot(doc(db, "tweets", id), (snapshot) => setPost(snapshot))
    },[db, id])

  return (
    <div>
          <div>
              <Head>
                  <title>NextJs Post Page</title>
                  <meta name="description" content="Generated by create next app" />
                  <link rel="icon" href="/favicon.ico" />
              </Head>
              <main className='flex min-h-screen mx-auto'>
                  {/* <Sidebar> */}
                  <Sidebar />

                  {/* <Post section> */}
                  <div className='xl:ml-[370px] border-r border-l border-gray-200 xl:min-w-[576px] sm:ml-[73px] grow '>
                      <div className='flex items-center space-x-2 py-2 px-3 sticky top-0 z-50 bg-white border-b border-gray-200'>
                        <div className="hover__effect flex items-center justify-center" onClick={()=> router.push("/")}>
                            <ArrowLeftIcon className="h-5 hover:translate-x-[-5px] duration-500 ease-out" />
                        </div>
                          <h2 className='text-lg sm:text-xl font-bold cursor-pointer'>Post</h2>
                          
                          {/* {
                            posts.map(post => (  
                                <Post post={post} />
                              ))
                          } */}

                        </div>
                        <Post id={id} post={post} />
                  </div>
                  

                  {/* <Widgets> */}
                  <Widgets newsData={newsData} whoToFollowData={whoToFollowData} />

                  {/* <Modal> */}
                  <CommentModal />

              </main>

          </div>
    </div>
  )
}

export default PostPage

export async function getServerSideProps() {
    const newsRes = await fetch('https://saurav.tech/NewsAPI/top-headlines/category/technology/fr.json')
    const newsData = await newsRes.json()

    const whoToFollowRes = await fetch('https://randomuser.me/api/?results=30&inc=name,picture,login');
    const whoToFollowData = await whoToFollowRes.json();

    return {
        props: {
            newsData,
            whoToFollowData
        }
    }
}