import React, {useEffect, useState} from 'react'
import { useRouter } from 'next/router'
import Sidebar from '../../components/Sidebar'
import Widgets from '../../components/Widgets'
import Head from 'next/head'
import CommentModal from '../../components/CommentModal'
import { ArrowLeftIcon } from '@heroicons/react/solid'
import Post from '../../components/Feed/Post'
import { db } from '../../firebase'
import { collection, doc, onSnapshot, orderBy, query } from 'firebase/firestore'
import Comments from '../../components/Comments'
import { AnimatePresence, motion } from 'framer-motion'

const PostPage = ({ newsData, whoToFollowData }) => {
    const router = useRouter();
    const { id } = router.query;
    const [post, setPost] = useState(null);
    const [comment, setComment] = useState([]);

    // get the post data
    useEffect(()=> {
        onSnapshot(doc(db, "tweets", id), (snapshot) => setPost(snapshot))
    },[db, id])

    //get the post comments
    useEffect(()=> {
        onSnapshot(query(collection(db, "tweets", id, "comments"), orderBy("timestamp", "desc")), (snapshot)=> setComment(snapshot.docs))
    },[db, id])

  return (
    <div>
          <div>
              <Head>
                  <title>NextJs Post Page</title>
                  <meta name="description" content="Generated by create next app" />
                  <link rel="icon" href="/favicon.ico" />
              </Head>
              <main className='flex min-h-screen mx-auto'>
                  {/* <Sidebar> */}
                  <Sidebar />

                  {/* <Post section> */}
                  <div className='xl:ml-[370px] border-r border-l border-gray-200 xl:min-w-[576px] sm:ml-[73px] grow '>
                      <div className='flex items-center space-x-2 py-2 px-3 sticky top-0 z-50 bg-white border-b border-gray-200'>
                        <div className="hover__effect flex items-center justify-center" onClick={()=> router.push("/")}>
                            <ArrowLeftIcon className="h-5 hover:translate-x-[-5px] duration-500 ease-out" />
                        </div>
                          <h2 className='text-lg sm:text-xl font-bold cursor-pointer'>Post</h2>
                        </div>

                        <Post id={id} post={post} />
                        {
                            comment.length > 0 && (
                                <div className="">
                                    <AnimatePresence>
                                    {
                                       comment.map(comment => (
                                           <motion.div
                                               key={comment.id}
                                               initial={{ opacity: 0 }}
                                               animate={{ opacity: 1 }}
                                               exit={{ opacity: 0 }}
                                               transition={{ duration: 1 }}
                                           >
                                            <Comments 
                                                key={comment.id} 
                                                commentId={comment.id} 
                                                originalPostId={id}
                                                comment={comment.data()}
                                            />
                                            </motion.div>
                                        )) 
                                    }
                                  </AnimatePresence>
                                </div>
                            )
                        }
                        
                        
                  </div>
                  

                  {/* <Widgets> */}
                  <Widgets newsData={newsData} whoToFollowData={whoToFollowData} />

                  {/* <Modal> */}
                  <CommentModal />

              </main>

          </div>
    </div>
  )
}

export default PostPage

export async function getServerSideProps() {
    const newsRes = await fetch('https://saurav.tech/NewsAPI/top-headlines/category/technology/fr.json')
    const newsData = await newsRes.json()

    const whoToFollowRes = await fetch('https://randomuser.me/api/?results=30&inc=name,picture,login');
    const whoToFollowData = await whoToFollowRes.json();

    return {
        props: {
            newsData,
            whoToFollowData
        }
    }
}